name             'generic-vhosts'
maintainer       'OSU Open Source Lab'
maintainer_email 'systems@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures generic-vhosts'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.17'
depends          'yum'
depends          'apache2'
depends          'base'
