cookbook "base", git: "https://github.com/osuosl-cookbooks/base.git"
cookbook "firewall", git: "https://github.com/osuosl-cookbooks/firewall.git"
cookbook "monitoring", git: "https://github.com/osuosl/chef-repo.git", rel: "osl-cookbooks/monitoring"
cookbook "aliases", git: "https://github.com/osuosl-cookbooks/aliases.git"
cookbook "munin", git: "https://github.com/opscode-cookbooks/munin.git"
cookbook "osl-munin", git: "https://github.com/osuosl-cookbooks/osl-munin.git"
cookbook "osl-nginx", git: "https://github.com/osuosl-cookbooks/osl-nginx.git"

site :opscode

metadata
