name             'orvsd-web'
maintainer       'OSU Open Source Lab'
maintainer_email 'rudy@grigar.net'
license          'All rights reserved'
description      'Installs/Configures orvsd-web'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'
depends          'base'
depends          'nginx'
depends          'yum'
depends          'firewall'
depends          'monitoring'
