site :opscode

cookbook "apache2"
cookbook "apt"
cookbook "ark"
cookbook "aws"
cookbook "berkshelf-api"
cookbook "bluepill"
cookbook "build-essential"
cookbook "certificate"
cookbook "chef-client"
cookbook "chef_handler"
cookbook "chef-server"
cookbook "cpu"
cookbook "cron"
cookbook "daemontools"
cookbook "database"
cookbook "dmg"
cookbook "erlang"
cookbook "git"
cookbook "haproxy"
cookbook "homebrew"
cookbook "hostsfile"
cookbook "iptables"
cookbook "java"
cookbook "jenkins"
cookbook "line"
cookbook "logrotate"
cookbook "logstash",
  github: "lusis/chef-logstash",
  tag: "0.8.1"
cookbook "lsyncd"
cookbook "magic_shell"
cookbook "memcached"
cookbook "monit"
cookbook "munin"
cookbook "mysql"
cookbook "nfs"
cookbook "nginx"
cookbook "ntp"
cookbook "ohai"
cookbook "omnibus_updater"
cookbook "openssh"
cookbook "openssl"
cookbook "pacman"
cookbook "passenger_apache2"
cookbook "perl"
cookbook "php"
cookbook "postfix"
cookbook "postgresql"
cookbook "python"
cookbook "rabbitmq"
cookbook "resolver"
cookbook "rsync"
cookbook "rsyslog"
cookbook "runit"
cookbook "rvm"
cookbook "selinux"
cookbook "simple_iptables"
cookbook "sqlite"
cookbook "sudo"
cookbook "supervisor"
cookbook "sysctl"
cookbook "user"
cookbook "windows"
cookbook "xfs"
cookbook "xml"
cookbook "yum"

cookbook "openstack-block-storage",
  github: "stackforge/cookbook-openstack-block-storage",
  branch: "stable/havana"
cookbook "openstack-common",
  github: "stackforge/cookbook-openstack-common",
  branch: "stable/havana"
cookbook "openstack-compute",
  github: "stackforge/cookbook-openstack-compute",
  branch: "stable/havana"
cookbook "openstack-dashboard",
  github: "stackforge/cookbook-openstack-dashboard",
  branch: "stable/havana"
cookbook "openstack-identity",
  github: "stackforge/cookbook-openstack-identity",
  branch: "stable/havana"
cookbook "openstack-image",
  github: "stackforge/cookbook-openstack-image",
  branch: "stable/havana"
cookbook "openstack-network",
  github: "stackforge/cookbook-openstack-network",
  branch: "stable/havana"
cookbook "openstack-object-storage",
  github: "stackforge/cookbook-openstack-object-storage",
  branch: "stable/havana"
cookbook "openstack-ops-database",
  github: "stackforge/cookbook-openstack-ops-database",
  branch: "stable/havana"
cookbook "openstack-ops-messaging",
  github: "stackforge/cookbook-openstack-ops-messaging",
  branch: "stable/havana"
cookbook "openstack-orchestration",
  github: "stackforge/cookbook-openstack-orchestration",
  branch: "stable/havana"
cookbook "openstack-telemetry",
  github: "stackforge/cookbook-openstack-telemetry",
  branch: "stable/havana"
