name             'goblin'
maintainer       'OSU Open Source Lab'
maintainer_email 'rudy@grigar.net'
license          'All rights reserved'
description      'Installs/Configures goblin'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'application'
depends          'application_python'
depends          'perl'
depends          'openssl'
depends          'supervisor'
depends          'rabbitmq'
depends          'postgresql'
depends          'apache2'
depends          'user'
depends          'simple_iptables'
depends          'memcached'
