source 'https://supermarket.chef.io'

solver :ruby, :required

# OSL Base deps
cookbook 'aliases', git: 'git@github.com:osuosl-cookbooks/aliases'
cookbook 'base', git: 'git@github.com:osuosl-cookbooks/base'
cookbook 'firewall', git: 'git@github.com:osuosl-cookbooks/firewall'
cookbook 'ganeti', git: 'git@github.com:osuosl-cookbooks/ganeti'
cookbook 'ibm-power', git: 'git@github.com:osuosl-cookbooks/ibm-power'
cookbook 'modules', git: 'git@github.com:osuosl-cookbooks/modules-cookbook'
cookbook 'munin', git: 'git@github.com:osuosl-cookbooks/munin'
cookbook 'openvpn', github: 'osuosl-cookbooks/openvpn'
cookbook 'osl-dhcp', git: 'git@github.com:osuosl-cookbooks/osl-dhcp'
cookbook 'osl-dns', git: 'git@github.com:osuosl-cookbooks/osl-dns'
cookbook 'osl-jenkins', git: 'git@github.com:osuosl-cookbooks/osl-jenkins'
cookbook 'osl-ganeti', git: 'git@github.com:osuosl-cookbooks/osl-ganeti'
cookbook 'osl-haproxy', git: 'git@github.com:osuosl-cookbooks/osl-haproxy'
cookbook 'osl-nagios', git: 'git@github.com:osuosl-cookbooks/osl-nagios'
cookbook 'osl-nrpe', git: 'git@github.com:osuosl-cookbooks/osl-nrpe'
cookbook 'osl-apache', git: 'git@github.com:osuosl-cookbooks/osl-apache'
cookbook 'osl-munin', git: 'git@github.com:osuosl-cookbooks/osl-munin'
cookbook 'osl-openstack', git: 'git@github.com:osuosl-cookbooks/osl-openstack'
cookbook 'osl-rsync', git: 'git@github.com:osuosl-cookbooks/osl-rsync'
cookbook 'osl-vpn', git: 'git@github.com:osuosl-cookbooks/osl-vpn'
cookbook 'resource_from_hash',
         git: 'git@github.com:osuosl-cookbooks/resource_from_hash'
cookbook 'statsd', github: 'att-cloud/cookbook-statsd'
cookbook 'yum-qemu-ev', git: 'git@github.com:osuosl-cookbooks/yum-qemu-ev.git'
cookbook 'provision_test', path: 'test/cookbooks/provision_test'
cookbook 'selinux',
         github: 'skottler/selinux',
         ref: '5c92a6dcbf'

# WIP patches
# %w(
# ).each do |cb|
#   cookbook "openstack-#{cb}",
#            github: "osuosl-cookbooks/cookbook-openstack-#{cb}",
#            branch: 'stable/mitaka'
# end

# Openstack deps
%w(
  block-storage
  common
  compute
  dashboard
  identity
  image
  integration-test
  network
  ops-database
  ops-messaging
  orchestration
  telemetry
).each do |cb|
  #  dashboard
  cookbook "openstack-#{cb}",
           github: "openstack/cookbook-openstack-#{cb}",
           tag: 'mitaka-eol'
end

metadata
