name             'provisioning'
maintainer       'Oregon State University'
maintainer_email 'systems@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures provisioning'
long_description 'Installs/Configures provisioning'
version          '0.0.1'

depends 'base'
depends 'firewall'
depends 'osl-fail2ban'
depends 'osl-ganeti'
depends 'osl-openstack'
depends 'osl-selinux'
