name             'base'
maintainer       'OSU Open Source Lab'
maintainer_email 'rudy@osuosl.org'
license          'All rights reserved'
description      'Installs/Configures base packages'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.5'
depends          'chef_handler'
depends          'user'
depends          'openssh'
depends          'yum'
depends          'apt'
depends          'selinux'